name: Fork Setup Test

on:
  workflow_dispatch:

jobs:
  test-fork-setup:
    runs-on: ubuntu-latest
    # Keine Bedingung - läuft immer
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Test repository detection
      run: |
        echo "Current repository: ${{ github.repository }}"
        echo "Repository owner: ${{ github.repository_owner }}"
        echo "Repository name: ${{ github.event.repository.name }}"
        
        if [ "${{ github.repository }}" = "redpop/claude-code-slash-commands" ]; then
          echo "This is the ORIGINAL repository"
        else
          echo "This is a FORK"
        fi

    - name: Check what would be updated
      run: |
        echo "Would update .claude-commands.json with:"
        echo "  repo_owner: ${{ github.repository_owner }}"
        echo "  repo_name: ${{ github.event.repository.name }}"
        
        echo ""
        echo "Would create these labels:"
        echo "  - fork-configuration"
        echo "  - custom-command"  
        echo "  - upstream-sync"
        
        echo ""
        echo "Would create sync-upstream.yml workflow"